version: '3.5'

services: 
##################
## 网关和注册中心
##################
  etcd: #etcd
    image: bitnami/etcd:3.4.15
    environment: 
      ALLOW_NONE_AUTHENTICATION: 'yes'
    networks: 
      - my-bridge

  etcd-web-ui: #etcd web ui
    image: deltaprojects/etcdkeeper:latest
    networks:
      - my-bridge
    depends_on:
      - etcd

  micro-gateway: #micro网关
    image: micro/micro:v2.9.3
    ports: 
      - 8080:8080
    environment: 
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: etcd:2379
    networks: 
      - my-bridge
    command: '--client_retries 0 api' # --handler=api
    depends_on: 
      - etcd

  micro-web: #micro web界面
    image: micro/micro:v2.9.3
    ports: 
      - 8082:8082
    environment: 
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: etcd:2379
    networks: 
      - my-bridge
    command: web
    depends_on: 
      - etcd
#################
# app-view服务
#################
  app-view-service:
    image: chengche123/service-app-view-grpc:1.0
    environment: 
      COMIC_REGISTRY_ADDR: etcd:2379
      COMIC_MYSQL_DSN: root:qwe123456.@tcp(212.129.236.77:3306)/comic
    networks: 
      - my-bridge
    depends_on: 
      - etcd
#################
# auth服务
#################
  auth-service:
    image: chengche123/service-auth-grpc:1.0
    environment: 
      COMIC_REGISTRY_ADDR: etcd:2379
      COMIC_MYSQL_DSN: root:qwe123456.@tcp(212.129.236.77:3306)/comic
    networks: 
      - my-bridge
    depends_on: 
      - etcd
#################
# comic服务
#################
  comic-service:
    image: chengche123/service-comic-grpc:1.0
    environment: 
      COMIC_REGISTRY_ADDR: etcd:2379
      COMIC_MYSQL_DSN: root:qwe123456.@tcp(212.129.236.77:3306)/comic
    networks: 
      - my-bridge
    depends_on: 
      - etcd
#################
# news服务
#################
  news-service:
    image: chengche123/service-news-grpc:1.0
    environment: 
      COMIC_REGISTRY_ADDR: etcd:2379
      COMIC_MYSQL_DSN: root:qwe123456.@tcp(212.129.236.77:3306)/comic
    networks: 
      - my-bridge
    depends_on: 
      - etcd

networks: 
  my-bridge: 

