// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ComicService service

func NewComicServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ComicService service

type ComicService interface {
	ListComicInfo(ctx context.Context, in *ListComicInfoRequest, opts ...client.CallOption) (*ListComicInfoResponse, error)
}

type comicService struct {
	c    client.Client
	name string
}

func NewComicService(name string, c client.Client) ComicService {
	return &comicService{
		c:    c,
		name: name,
	}
}

func (c *comicService) ListComicInfo(ctx context.Context, in *ListComicInfoRequest, opts ...client.CallOption) (*ListComicInfoResponse, error) {
	req := c.c.NewRequest(c.name, "ComicService.ListComicInfo", in)
	out := new(ListComicInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ComicService service

type ComicServiceHandler interface {
	ListComicInfo(context.Context, *ListComicInfoRequest, *ListComicInfoResponse) error
}

func RegisterComicServiceHandler(s server.Server, hdlr ComicServiceHandler, opts ...server.HandlerOption) error {
	type comicService interface {
		ListComicInfo(ctx context.Context, in *ListComicInfoRequest, out *ListComicInfoResponse) error
	}
	type ComicService struct {
		comicService
	}
	h := &comicServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ComicService{h}, opts...))
}

type comicServiceHandler struct {
	ComicServiceHandler
}

func (h *comicServiceHandler) ListComicInfo(ctx context.Context, in *ListComicInfoRequest, out *ListComicInfoResponse) error {
	return h.ComicServiceHandler.ListComicInfo(ctx, in, out)
}
