// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: app.view.v1.api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListHomeMoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryName string `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	PageIndex    int32  `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize     int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListHomeMoRequest) Reset() {
	*x = ListHomeMoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_view_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHomeMoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHomeMoRequest) ProtoMessage() {}

func (x *ListHomeMoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_view_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHomeMoRequest.ProtoReflect.Descriptor instead.
func (*ListHomeMoRequest) Descriptor() ([]byte, []int) {
	return file_app_view_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *ListHomeMoRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ListHomeMoRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *ListHomeMoRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FeedComicMo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Authors        string `protobuf:"bytes,3,opt,name=authors,proto3" json:"authors,omitempty"`
	Status         string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Cover          string `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Types          string `protobuf:"bytes,6,opt,name=types,proto3" json:"types,omitempty"`
	LastUpdatetime int32  `protobuf:"varint,7,opt,name=last_updatetime,json=lastUpdatetime,proto3" json:"last_updatetime,omitempty"`
	Num            int32  `protobuf:"varint,8,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *FeedComicMo) Reset() {
	*x = FeedComicMo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_view_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedComicMo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedComicMo) ProtoMessage() {}

func (x *FeedComicMo) ProtoReflect() protoreflect.Message {
	mi := &file_app_view_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedComicMo.ProtoReflect.Descriptor instead.
func (*FeedComicMo) Descriptor() ([]byte, []int) {
	return file_app_view_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *FeedComicMo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FeedComicMo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedComicMo) GetAuthors() string {
	if x != nil {
		return x.Authors
	}
	return ""
}

func (x *FeedComicMo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FeedComicMo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *FeedComicMo) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

func (x *FeedComicMo) GetLastUpdatetime() int32 {
	if x != nil {
		return x.LastUpdatetime
	}
	return 0
}

func (x *FeedComicMo) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type BannerMo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sticky     uint32 `protobuf:"varint,2,opt,name=sticky,proto3" json:"sticky,omitempty"`
	Type       string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title      string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle   string `protobuf:"bytes,5,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Url        string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Cover      string `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	CreateTime string `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *BannerMo) Reset() {
	*x = BannerMo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_view_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerMo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerMo) ProtoMessage() {}

func (x *BannerMo) ProtoReflect() protoreflect.Message {
	mi := &file_app_view_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerMo.ProtoReflect.Descriptor instead.
func (*BannerMo) Descriptor() ([]byte, []int) {
	return file_app_view_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *BannerMo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BannerMo) GetSticky() uint32 {
	if x != nil {
		return x.Sticky
	}
	return 0
}

func (x *BannerMo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BannerMo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BannerMo) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *BannerMo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BannerMo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *BannerMo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type CategoryMo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *CategoryMo) Reset() {
	*x = CategoryMo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_view_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryMo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryMo) ProtoMessage() {}

func (x *CategoryMo) ProtoReflect() protoreflect.Message {
	mi := &file_app_view_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryMo.ProtoReflect.Descriptor instead.
func (*CategoryMo) Descriptor() ([]byte, []int) {
	return file_app_view_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryMo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryMo) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListHomeMoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerList   []*BannerMo    `protobuf:"bytes,1,rep,name=banner_list,json=bannerList,proto3" json:"banner_list,omitempty"`
	CategoryList []*CategoryMo  `protobuf:"bytes,2,rep,name=category_list,json=categoryList,proto3" json:"category_list,omitempty"`
	ComicList    []*FeedComicMo `protobuf:"bytes,3,rep,name=comic_list,json=comicList,proto3" json:"comic_list,omitempty"`
}

func (x *ListHomeMoResponse) Reset() {
	*x = ListHomeMoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_view_v1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHomeMoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHomeMoResponse) ProtoMessage() {}

func (x *ListHomeMoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_view_v1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHomeMoResponse.ProtoReflect.Descriptor instead.
func (*ListHomeMoResponse) Descriptor() ([]byte, []int) {
	return file_app_view_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *ListHomeMoResponse) GetBannerList() []*BannerMo {
	if x != nil {
		return x.BannerList
	}
	return nil
}

func (x *ListHomeMoResponse) GetCategoryList() []*CategoryMo {
	if x != nil {
		return x.CategoryList
	}
	return nil
}

func (x *ListHomeMoResponse) GetComicList() []*FeedComicMo {
	if x != nil {
		return x.ComicList
	}
	return nil
}

var File_app_view_v1_api_proto protoreflect.FileDescriptor

var file_app_view_v1_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x69, 0x65,
	0x77, 0x2e, 0x76, 0x31, 0x22, 0x74, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x6d, 0x65,
	0x4d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x0b, 0x46,
	0x65, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x69, 0x63, 0x4d, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x27,
	0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0xc1, 0x01, 0x0a, 0x08, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a,
	0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4d, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc3, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f,
	0x6d, 0x65, 0x4d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b,
	0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e,
	0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x6f, 0x52, 0x0a, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x4d, 0x6f, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x69, 0x63, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x69, 0x65,
	0x77, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x69, 0x63, 0x4d, 0x6f,
	0x52, 0x09, 0x63, 0x6f, 0x6d, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x5f, 0x0a, 0x0e, 0x41,
	0x70, 0x70, 0x76, 0x69, 0x65, 0x77, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x6d, 0x65, 0x4d, 0x6f, 0x12, 0x1e, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f,
	0x6d, 0x65, 0x4d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f,
	0x6d, 0x65, 0x4d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_view_v1_api_proto_rawDescOnce sync.Once
	file_app_view_v1_api_proto_rawDescData = file_app_view_v1_api_proto_rawDesc
)

func file_app_view_v1_api_proto_rawDescGZIP() []byte {
	file_app_view_v1_api_proto_rawDescOnce.Do(func() {
		file_app_view_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_view_v1_api_proto_rawDescData)
	})
	return file_app_view_v1_api_proto_rawDescData
}

var file_app_view_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_app_view_v1_api_proto_goTypes = []interface{}{
	(*ListHomeMoRequest)(nil),  // 0: app.view.v1.ListHomeMoRequest
	(*FeedComicMo)(nil),        // 1: app.view.v1.FeedComicMo
	(*BannerMo)(nil),           // 2: app.view.v1.BannerMo
	(*CategoryMo)(nil),         // 3: app.view.v1.CategoryMo
	(*ListHomeMoResponse)(nil), // 4: app.view.v1.ListHomeMoResponse
}
var file_app_view_v1_api_proto_depIdxs = []int32{
	2, // 0: app.view.v1.ListHomeMoResponse.banner_list:type_name -> app.view.v1.BannerMo
	3, // 1: app.view.v1.ListHomeMoResponse.category_list:type_name -> app.view.v1.CategoryMo
	1, // 2: app.view.v1.ListHomeMoResponse.comic_list:type_name -> app.view.v1.FeedComicMo
	0, // 3: app.view.v1.AppviewService.ListHomeMo:input_type -> app.view.v1.ListHomeMoRequest
	4, // 4: app.view.v1.AppviewService.ListHomeMo:output_type -> app.view.v1.ListHomeMoResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_view_v1_api_proto_init() }
func file_app_view_v1_api_proto_init() {
	if File_app_view_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_view_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHomeMoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_view_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedComicMo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_view_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerMo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_view_v1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryMo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_view_v1_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHomeMoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_view_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_view_v1_api_proto_goTypes,
		DependencyIndexes: file_app_view_v1_api_proto_depIdxs,
		MessageInfos:      file_app_view_v1_api_proto_msgTypes,
	}.Build()
	File_app_view_v1_api_proto = out.File
	file_app_view_v1_api_proto_rawDesc = nil
	file_app_view_v1_api_proto_goTypes = nil
	file_app_view_v1_api_proto_depIdxs = nil
}
