version: '3.5'

services: 
  mysql:
    image: chengche123/server-db:1.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwe123456. # 线上得改
    volumes:
      - mysql-data:/var/lib/mysql
    networks: 
      - my-bridge
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # depends_on:
    
    
networks: 
  my-bridge: 

volumes:
  mysql-data:


