version: '3'

services: 
  etcd: #etcd
    image: bitnami/etcd:3.4.15
    ports: 
      - 2379:2379
    environment: 
      ALLOW_NONE_AUTHENTICATION: 'yes'
    networks: 
      - my-bridge

  micro-gateway: #micro网关
    image: micro/micro:v2.9.3
    ports: 
      - 8080:8080
    environment: 
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: etcd:2379
    command: api --handler=api
    networks: 
      - my-bridge

  micro-web: #micro web界面
    image: micro/micro:v2.9.3
    ports: 
      - 8082:8082
    environment: 
      MICRO_REGISTRY: etcd
      MICRO_REGISTRY_ADDRESS: etcd:2379
    command: web
    networks: 
      - my-bridge

networks: 
  my-bridge: 
